/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UkraineAlarm.Api;
using UkraineAlarm.Model;
using UkraineAlarm.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing AlertRegionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertRegionModelTests
    {
        // TODO uncomment below to declare an instance variable for AlertRegionModel
        //private AlertRegionModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertRegionModel
            //instance = new AlertRegionModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertRegionModel
        /// </summary>
        [Test]
        public void AlertRegionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertRegionModel
            //Assert.IsInstanceOfType<AlertRegionModel> (instance, "variable 'instance' is a AlertRegionModel");
        }


        /// <summary>
        /// Test the property 'RegionId'
        /// </summary>
        [Test]
        public void RegionIdTest()
        {
            // TODO unit test for the property 'RegionId'
        }
        /// <summary>
        /// Test the property 'RegionType'
        /// </summary>
        [Test]
        public void RegionTypeTest()
        {
            // TODO unit test for the property 'RegionType'
        }
        /// <summary>
        /// Test the property 'RegionName'
        /// </summary>
        [Test]
        public void RegionNameTest()
        {
            // TODO unit test for the property 'RegionName'
        }
        /// <summary>
        /// Test the property 'RegionEngName'
        /// </summary>
        [Test]
        public void RegionEngNameTest()
        {
            // TODO unit test for the property 'RegionEngName'
        }
        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Test]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
        /// <summary>
        /// Test the property 'ActiveAlerts'
        /// </summary>
        [Test]
        public void ActiveAlertsTest()
        {
            // TODO unit test for the property 'ActiveAlerts'
        }

    }

}
