/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UkraineAlarm.Api;
using UkraineAlarm.Model;
using UkraineAlarm.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing AlertModification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertModificationTests
    {
        // TODO uncomment below to declare an instance variable for AlertModification
        //private AlertModification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertModification
            //instance = new AlertModification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertModification
        /// </summary>
        [Test]
        public void AlertModificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertModification
            //Assert.IsInstanceOfType<AlertModification> (instance, "variable 'instance' is a AlertModification");
        }


        /// <summary>
        /// Test the property 'LastActionIndex'
        /// </summary>
        [Test]
        public void LastActionIndexTest()
        {
            // TODO unit test for the property 'LastActionIndex'
        }

    }

}
