/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UkraineAlarm.Api;
using UkraineAlarm.Model;
using UkraineAlarm.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing RegionAlarmsHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegionAlarmsHistoryTests
    {
        // TODO uncomment below to declare an instance variable for RegionAlarmsHistory
        //private RegionAlarmsHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegionAlarmsHistory
            //instance = new RegionAlarmsHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegionAlarmsHistory
        /// </summary>
        [Test]
        public void RegionAlarmsHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegionAlarmsHistory
            //Assert.IsInstanceOfType<RegionAlarmsHistory> (instance, "variable 'instance' is a RegionAlarmsHistory");
        }


        /// <summary>
        /// Test the property 'RegionId'
        /// </summary>
        [Test]
        public void RegionIdTest()
        {
            // TODO unit test for the property 'RegionId'
        }
        /// <summary>
        /// Test the property 'RegionName'
        /// </summary>
        [Test]
        public void RegionNameTest()
        {
            // TODO unit test for the property 'RegionName'
        }
        /// <summary>
        /// Test the property 'Alarms'
        /// </summary>
        [Test]
        public void AlarmsTest()
        {
            // TODO unit test for the property 'Alarms'
        }

    }

}
