/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UkraineAlarm.Api;
using UkraineAlarm.Model;
using UkraineAlarm.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing TimeSpan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimeSpanTests
    {
        // TODO uncomment below to declare an instance variable for TimeSpan
        //private TimeSpan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimeSpan
            //instance = new TimeSpan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimeSpan
        /// </summary>
        [Test]
        public void TimeSpanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimeSpan
            //Assert.IsInstanceOfType<TimeSpan> (instance, "variable 'instance' is a TimeSpan");
        }


        /// <summary>
        /// Test the property 'Ticks'
        /// </summary>
        [Test]
        public void TicksTest()
        {
            // TODO unit test for the property 'Ticks'
        }
        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Test]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }
        /// <summary>
        /// Test the property 'Hours'
        /// </summary>
        [Test]
        public void HoursTest()
        {
            // TODO unit test for the property 'Hours'
        }
        /// <summary>
        /// Test the property 'Milliseconds'
        /// </summary>
        [Test]
        public void MillisecondsTest()
        {
            // TODO unit test for the property 'Milliseconds'
        }
        /// <summary>
        /// Test the property 'Minutes'
        /// </summary>
        [Test]
        public void MinutesTest()
        {
            // TODO unit test for the property 'Minutes'
        }
        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Test]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }
        /// <summary>
        /// Test the property 'TotalDays'
        /// </summary>
        [Test]
        public void TotalDaysTest()
        {
            // TODO unit test for the property 'TotalDays'
        }
        /// <summary>
        /// Test the property 'TotalHours'
        /// </summary>
        [Test]
        public void TotalHoursTest()
        {
            // TODO unit test for the property 'TotalHours'
        }
        /// <summary>
        /// Test the property 'TotalMilliseconds'
        /// </summary>
        [Test]
        public void TotalMillisecondsTest()
        {
            // TODO unit test for the property 'TotalMilliseconds'
        }
        /// <summary>
        /// Test the property 'TotalMinutes'
        /// </summary>
        [Test]
        public void TotalMinutesTest()
        {
            // TODO unit test for the property 'TotalMinutes'
        }
        /// <summary>
        /// Test the property 'TotalSeconds'
        /// </summary>
        [Test]
        public void TotalSecondsTest()
        {
            // TODO unit test for the property 'TotalSeconds'
        }

    }

}
