/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UkraineAlarm.Api;
using UkraineAlarm.Model;
using UkraineAlarm.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing WebHookModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebHookModelTests
    {
        // TODO uncomment below to declare an instance variable for WebHookModel
        //private WebHookModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebHookModel
            //instance = new WebHookModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebHookModel
        /// </summary>
        [Test]
        public void WebHookModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebHookModel
            //Assert.IsInstanceOfType<WebHookModel> (instance, "variable 'instance' is a WebHookModel");
        }


        /// <summary>
        /// Test the property 'WebHookUrl'
        /// </summary>
        [Test]
        public void WebHookUrlTest()
        {
            // TODO unit test for the property 'WebHookUrl'
        }

    }

}
