/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = UkraineAlarm.Client.SwaggerDateConverter;
namespace UkraineAlarm.Model
{
    /// <summary>
    /// AlertModification
    /// </summary>
    [DataContract]
        public partial class AlertModification :  IEquatable<AlertModification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlertModification" /> class.
        /// </summary>
        /// <param name="lastActionIndex">lastActionIndex.</param>
        public AlertModification(long? lastActionIndex = default(long?))
        {
            this.LastActionIndex = lastActionIndex;
        }
        
        /// <summary>
        /// Gets or Sets LastActionIndex
        /// </summary>
        [DataMember(Name="lastActionIndex", EmitDefaultValue=false)]
        public long? LastActionIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlertModification {\n");
            sb.Append("  LastActionIndex: ").Append(LastActionIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlertModification);
        }

        /// <summary>
        /// Returns true if AlertModification instances are equal
        /// </summary>
        /// <param name="input">Instance of AlertModification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlertModification input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LastActionIndex == input.LastActionIndex ||
                    (this.LastActionIndex != null &&
                    this.LastActionIndex.Equals(input.LastActionIndex))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LastActionIndex != null)
                    hashCode = hashCode * 59 + this.LastActionIndex.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
