/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = UkraineAlarm.Client.SwaggerDateConverter;
namespace UkraineAlarm.Model
{
    /// <summary>
    /// Defines AlertType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum AlertType
    {
        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 1,
        /// <summary>
        /// Enum AIR for value: AIR
        /// </summary>
        [EnumMember(Value = "AIR")]
        AIR = 2,
        /// <summary>
        /// Enum ARTILLERY for value: ARTILLERY
        /// </summary>
        [EnumMember(Value = "ARTILLERY")]
        ARTILLERY = 3,
        /// <summary>
        /// Enum URBANFIGHTS for value: URBAN_FIGHTS
        /// </summary>
        [EnumMember(Value = "URBAN_FIGHTS")]
        URBANFIGHTS = 4,
        /// <summary>
        /// Enum CHEMICAL for value: CHEMICAL
        /// </summary>
        [EnumMember(Value = "CHEMICAL")]
        CHEMICAL = 5,
        /// <summary>
        /// Enum NUCLEAR for value: NUCLEAR
        /// </summary>
        [EnumMember(Value = "NUCLEAR")]
        NUCLEAR = 6,
        /// <summary>
        /// Enum INFO for value: INFO
        /// </summary>
        [EnumMember(Value = "INFO")]
        INFO = 7    }
}
