/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = UkraineAlarm.Client.SwaggerDateConverter;
namespace UkraineAlarm.Model
{
    /// <summary>
    /// Defines v2RegionType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum V2RegionType
    {
        /// <summary>
        /// Enum State for value: State
        /// </summary>
        [EnumMember(Value = "State")]
        State = 1,
        /// <summary>
        /// Enum District for value: District
        /// </summary>
        [EnumMember(Value = "District")]
        District = 2,
        /// <summary>
        /// Enum Community for value: Community
        /// </summary>
        [EnumMember(Value = "Community")]
        Community = 3,
        /// <summary>
        /// Enum Null for value: Null
        /// </summary>
        [EnumMember(Value = "Null")]
        Null = 4    }
}
