/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using UkraineAlarm.Client;
using UkraineAlarm.Model;

namespace UkraineAlarm.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IRegionsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Повертає список усіх областей, регіонів та міст
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>RegionsViewModel</returns>
        RegionsViewModel ApiV3RegionsGet ();

        /// <summary>
        /// Повертає список усіх областей, регіонів та міст
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of RegionsViewModel</returns>
        ApiResponse<RegionsViewModel> ApiV3RegionsGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Повертає список усіх областей, регіонів та міст
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of RegionsViewModel</returns>
        System.Threading.Tasks.Task<RegionsViewModel> ApiV3RegionsGetAsync ();

        /// <summary>
        /// Повертає список усіх областей, регіонів та міст
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (RegionsViewModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<RegionsViewModel>> ApiV3RegionsGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class RegionsApi : IRegionsApi
    {
        private UkraineAlarm.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RegionsApi(String basePath)
        {
            this.Configuration = new UkraineAlarm.Client.Configuration { BasePath = basePath };

            ExceptionFactory = UkraineAlarm.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class
        /// </summary>
        /// <returns></returns>
        public RegionsApi()
        {
            this.Configuration = UkraineAlarm.Client.Configuration.Default;

            ExceptionFactory = UkraineAlarm.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RegionsApi(UkraineAlarm.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = UkraineAlarm.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = UkraineAlarm.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public UkraineAlarm.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public UkraineAlarm.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Повертає список усіх областей, регіонів та міст 
        /// </summary>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>RegionsViewModel</returns>
        public RegionsViewModel ApiV3RegionsGet ()
        {
             ApiResponse<RegionsViewModel> localVarResponse = ApiV3RegionsGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Повертає список усіх областей, регіонів та міст 
        /// </summary>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of RegionsViewModel</returns>
        public ApiResponse< RegionsViewModel > ApiV3RegionsGetWithHttpInfo ()
        {

            var localVarPath = "/api/v3/regions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV3RegionsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RegionsViewModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RegionsViewModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RegionsViewModel)));
        }

        /// <summary>
        /// Повертає список усіх областей, регіонів та міст 
        /// </summary>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of RegionsViewModel</returns>
        public async System.Threading.Tasks.Task<RegionsViewModel> ApiV3RegionsGetAsync ()
        {
             ApiResponse<RegionsViewModel> localVarResponse = await ApiV3RegionsGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Повертає список усіх областей, регіонів та міст 
        /// </summary>
        /// <exception cref="UkraineAlarm.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (RegionsViewModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RegionsViewModel>> ApiV3RegionsGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v3/regions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (Token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV3RegionsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RegionsViewModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RegionsViewModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RegionsViewModel)));
        }

    }
}
