/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using UkraineAlarm.Client;
using UkraineAlarm.Api;
using UkraineAlarm.Model;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing RegionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RegionsApiTests
    {
        private RegionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RegionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RegionsApi
            //Assert.IsInstanceOfType(typeof(RegionsApi), instance, "instance is a RegionsApi");
        }

        /// <summary>
        /// Test ApiV3RegionsGet
        /// </summary>
        [Test]
        public void ApiV3RegionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiV3RegionsGet();
            //Assert.IsInstanceOf<RegionsViewModel> (response, "response is RegionsViewModel");
        }
    }

}
