/* 
 * Ukraine Alert API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using UkraineAlarm.Client;
using UkraineAlarm.Api;
using UkraineAlarm.Model;

namespace UkraineAlarm.Test
{
    /// <summary>
    ///  Class for testing WebHookApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WebHookApiTests
    {
        private WebHookApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WebHookApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebHookApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WebHookApi
            //Assert.IsInstanceOfType(typeof(WebHookApi), instance, "instance is a WebHookApi");
        }

        /// <summary>
        /// Test ApiV3WebhookDelete
        /// </summary>
        [Test]
        public void ApiV3WebhookDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebHookModel body = null;
            //instance.ApiV3WebhookDelete(body);
            
        }
        /// <summary>
        /// Test ApiV3WebhookPatch
        /// </summary>
        [Test]
        public void ApiV3WebhookPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebHookModel body = null;
            //instance.ApiV3WebhookPatch(body);
            
        }
        /// <summary>
        /// Test ApiV3WebhookPost
        /// </summary>
        [Test]
        public void ApiV3WebhookPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebHookModel body = null;
            //var response = instance.ApiV3WebhookPost(body);
            //Assert.IsInstanceOf<AlertRegionModel> (response, "response is AlertRegionModel");
        }
    }

}
